previewsEnabled: true

services:
  - type: web
    name: flaskapp
    env: python
    region: oregon
    plan: starter
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
